[tool.poetry]
name = "labello"
version = "0.2.1"
description = "A webinterface to print labels"
authors = ["telegnom <max@telegnom.org>"]
license = "MIT"
include = ["labello/*", "labello/node_modules/@mdi/font/*"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Flask = "^3.1.3"
Pillow = "^12.3.0"
Flask-Bootstrap4 = "^4.0.2"
qrcode = "^8.2"
PyYAML = "^6.0.3"
gunicorn = "^26.2.0"
brother-ql-next = "^0.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
